dataset:
  name: arcene
  root: "src/data/processed/arcene"
  fold_scheme: stratified
  target_column: target
  id_column: null

selectors:
  - variance
  - anova
  - l1_logreg
  - tree_importance
  - mi
  - mrmr

models:
  - logreg
  - hgbt


k_values: [ 5,10,20, 35, 50, 75, 100, 150, 200]

cv_outer_folds: 3
cv_repeats: 1
seed: 236040
tracking_uri: "mlruns"
